/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Payal Malotra' at '10/31/16 1:25 AM' with Gradle 3.1
 *
 * @author Payal Malotra, @date 10/31/16 1:25 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
